<?

$majors=array("Accounting",
	"Accounting Technology",
	"Adolescent and Young Adult Education",
	"Africana Studies",
	"American Studies",
	"Anthropology",
	"Applied Organizational Technology",
	"Art",
	"Art History",
	"Asian Studies",
	"Astronomy",
	"Biochemistry",
	"Bioengineering",
	"Biology",
	"Business Management Technology",
	"Chemical Engineering",
	"Chemistry",
	"Civil Engineering",
	"Communication",
	"Computer Network Administration",
	"Computer Science and Engineering",
	"Computer Science and Engineering Technology",
	"Computer Software Specialist Technology",
	"Construction Engineering Technology",
	"Cosmetic Science and Formulation Design",
	"Criminal Justice",
	"Digital Marketing",
	"Disability Studies",
	"Early Childhood Education (Pre-K-3)",
	"Economics",
	"Electrical Engineering",
	"Electrical Engineering Technology",
	"English",
	"Entrepreneurship, Family, and Small Business",
	"Environmental Engineering",
	"Environmental Sciences",
	"Environmental Studies",
	"Exercise Science",
	"Family Nurse Practitioner Primary Care",
	"Film and Video",
	"Finance",
	"Financial Services",
	"French",
	"General Studies",
	"General Studies (2-year)",
	"Geography and Planning",
	"Geology",
	"German",
	"Global Studies",
	"Health Care Policy and Administration",
	"Health Information Administration",
	"History",
	"Human Resource Management",
	"Individualized Programs",
	"Information Services and Support",
	"Information Systems",
	"Information Technology",
	"International Business",
	"Law and Social Thought",
	"Liberal Studies",
	"Management",
	"Marketing",
	"Mathematics",
	"Mechanical Engineering",
	"Mechanical Engineering Technology",
	"Media Communication",
	"Medical Technology",
	"Medicinal and Biological Chemistry",
	"Middle Childhood Education (4-9)",
	"Middle East Studies",
	"Multi-Age Education (Pre K-12)",
	"Music",
	"Nursing",
	"Organizational Leadership and Management",
	"Paralegal Studies",
	"Paralegal Studies (2-year)",
	"Pharmaceutics",
	"Pharmacology and Toxicology",
	"Pharmacy Administration",
	"Philosophy",
	"Physics",
	"Political Science",
	"Pre-Business",
	"Pre-Law",
	"Pre-Medical, Pre-Dental, Pre-Veterinary, Pre-Optometry",
	"Pre-Pharmacy",
	"Professional Sales",
	"Professional Studies",
	"Programming and Software Development",
	"Psychology",
	"Public Health",
	"Recreational Therapy",
	"Religious Studies",
	"Respiratory Care",
	"Social Work",
	"Sociology",
	"Spanish",
	"Special Education Intervention Specialist",
	"Speech-Language Pathology",
	"Supply Chain Management",
	"Theatre",
	"Undecided",
	"Urban Studies",
	"Visual Arts",
	"Women's and Gender Studies");
	
?>